# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.

import _ArnoldiMatrix
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class ArnoldiMatrix(object):
    """Proxy of C++ ArnoldiMatrix class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self, Teuchos::SerialDenseMatrix<(int,double)> A, bool v=True, 
            double rT=1E-10, double iT=1E-12) -> ArnoldiMatrix
        __init__(self, Teuchos::SerialDenseMatrix<(int,double)> A, bool v=True, 
            double rT=1E-10) -> ArnoldiMatrix
        __init__(self, Teuchos::SerialDenseMatrix<(int,double)> A, bool v=True) -> ArnoldiMatrix
        __init__(self, Teuchos::SerialDenseMatrix<(int,double)> A) -> ArnoldiMatrix
        """
        this = _ArnoldiMatrix.new_ArnoldiMatrix(*args)
        try: self.this.append(this)
        except: self.this = this
    def A(*args):
        """A(self) -> cSDM"""
        return _ArnoldiMatrix.ArnoldiMatrix_A(*args)

    def arnoldi(*args):
        """arnoldi(self, dSDV q, int I)"""
        return _ArnoldiMatrix.ArnoldiMatrix_arnoldi(*args)

    def ResTolerance(*args):
        """ResTolerance(self) -> double"""
        return _ArnoldiMatrix.ArnoldiMatrix_ResTolerance(*args)

    def InvTolerance(*args):
        """InvTolerance(self) -> double"""
        return _ArnoldiMatrix.ArnoldiMatrix_InvTolerance(*args)

    __swig_destroy__ = _ArnoldiMatrix.delete_ArnoldiMatrix
    __del__ = lambda self : None;
ArnoldiMatrix_swigregister = _ArnoldiMatrix.ArnoldiMatrix_swigregister
ArnoldiMatrix_swigregister(ArnoldiMatrix)



